FROM node:14.5.0-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm install --production
RUN npm install -g serve

COPY . /usr/src/app

CMD ["npm", "run", "build" ]
