version: '3.7'

services:
  web:
    build: ./music_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./music_service:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./music_service/.env.dev
    depends_on:
      - db

  client:
    build:
      context: ./music_client
    command: npm start .env.local
    ports:
      - 3000:3000
    volumes:
      - ./music_client:/usr/src/app
    depends_on:
      - web
    stdin_open: true

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./music_service/.env.dev

volumes:
  postgres_data: