version: '3.7'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  web:
    build: ./music_service
    container_name: web
    command: >
      sh -c
       "gunicorn music_service.wsgi:application --bind 0.0.0.0:8000 &&
         python manage.py makemigrations
         python manage.py migrate"
    volumes:
      - ./music_service:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./music_service/.env.prod
    depends_on:
      - db


  client:
    build:
      context: ./music_client
    container_name: client
    command: >
      sh -c "npm run build .env.production &&
            npm install -g serve &&
             serve -s build -l 3000"
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./music_client:/usr/src/app
    depends_on:
      - web

  nginx:
    build:
      context: ./nginx
    container_name: nginx_cerbot
    depends_on:
      - web
      - client
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: peter_joseph_simpson@hotmail.com
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt



volumes:
  postgres_data:
  media:
  static:
  letsencrypt:
