# Generated by Django 3.0.5 on 2020-07-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_newsitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='link_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
