# Generated by Django 3.0.5 on 2020-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_newsitem_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='link_title',
            field=models.CharField(max_length=255),
        ),
    ]
