# Generated by Django 3.0.5 on 2020-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200726_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='link_title',
            field=models.CharField(default='link', max_length=255),
        ),
    ]
