# Generated by Django 3.0.5 on 2020-08-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200727_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, null=True)),
                ('format', models.CharField(choices=[('DL', 'DL'), ('LP', 'LP'), ('CS', 'CS'), ('CD', 'CD')], default='DL', max_length=2)),
                ('mastered', models.CharField(max_length=255, null=True)),
                ('design', models.CharField(max_length=255, null=True)),
                ('recorded', models.CharField(max_length=255, null=True)),
                ('bandcamp_link', models.CharField(max_length=255, null=True)),
                ('soundcloud_link', models.CharField(max_length=255, null=True)),
                ('spotify_link', models.CharField(max_length=255, null=True)),
                ('buy_link', models.CharField(max_length=255, null=True)),
                ('press_release', models.TextField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Project')),
            ],
        ),
    ]
