# Generated by Django 3.0.5 on 2020-10-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20200805_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('link_title', models.CharField(default='link', max_length=255)),
                ('category', models.CharField(choices=[('Platform', 'Platform'), ('Mix', 'Mix'), ('Press', 'Press'), ('Project', 'Project')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='image',
            field=models.ImageField(blank=True, upload_to='release_images/'),
        ),
    ]
