# Generated by Django 3.0.5 on 2020-10-28 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_release_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='home_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='release',
            name='format',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DL', 'DL'), ('LP', 'LP'), ('CS', 'CS'), ('CD', 'CD')], default=['DL'], max_length=2), null=True, size=None),
        ),
    ]
