# Generated by Django 3.0.5 on 2020-10-28 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20201028_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
