# Generated by Django 3.0.5 on 2020-10-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20201028_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='src',
            new_name='image',
        ),
    ]
