# Generated by Django 3.0.7 on 2020-12-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20201115_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImage',
        ),
        migrations.AddField(
            model_name='image',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
