# Generated by Django 3.0.7 on 2020-12-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20201228_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='credit',
            new_name='title',
        ),
    ]
